# Простой Dockerfile без Actuator
FROM openjdk:17-jdk-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем все файлы
COPY . .

# Даем права на выполнение gradlew
RUN chmod +x ./gradlew

# Собираем приложение
RUN ./gradlew build -x test

# Запускаем приложение
CMD ["java", "-jar", "build/libs/wordle-0.0.1-SNAPSHOT.jar"]